name: test
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.os }} Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu"]
        ruby: ["3.3"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - if: matrix.os == 'ubuntu'
        run: sudo apt-get update -yq && sudo apt upgrade -yq && sudo apt-get upgrade # libjemalloc-dev
      - if: matrix.os == 'macos'
        run: brew update && brew install jemalloc
      - if: matrix.os == 'ubuntu'
        run: bundle exec rake jemalloc:build && bundle exec rake odgi:build
      - if: matrix.os == 'macos'
        run: CC=/opt/homebrew/opt/llvm/bin/clang CXX=/opt/homebrew/opt/llvm/bin/clang++ LDFLAGS=-L/opt/homebrew/lib bundle exec rake odgi:build
      - run: bundle exec rake compile
      - run: bundle exec rake test
